Resumed artifact installation fails
eclipse-kanto/software-update pull request #42
Opened 2022-09-26 11:36 UTC by gboyvalenkov-bosch

[#41] Resumed artifact installation fails

- fixed resuming of fully downloaded artifacts

Signed-off-by: Georgi Boyvalenkov <Georgi.Boyvalenkov@bosch.io>

2022-09-26 12:23 UTC, konstantina-gramatova requested changes

2022-09-26 21:56 UTC, e-grigorov requested changes

2022-09-26 21:56 UTC, e-grigorov commented on internal/storage/download.go
> +		if err := validate(to, artifact.HashType, artifact.HashValue); err == nil || retryCount == 0 {
This logic is duplicated with downloadFile method. Is it possible to check the size and offline and if they are equal, downloadFile can be ,called? Of course, the copy there should be skipped.

2022-09-27 06:47 UTC, konstantina-gramatova approved these changes

2022-09-27 06:49 UTC, e-grigorov approved these changes

2022-09-27 06:49 UTC, merged