[#64] Refactor flags implementation
eclipse-kanto/software-update pull request #65
Opened 2023-11-10 11:38 UTC by antonia-avramova

[#64] Refactor flags implementation

Signed-off-by: Antonia Avramova <antonia.avramova@bosch.io>

2023-11-14 07:03 UTC, dimitar-dimitrow requested changes
@antonia-avramova could you use the dev-m5 branch as base, or exclude the not needed commits with a rebase.

2023-11-14 11:57 UTC, dimitar-dimitrow commented on internal/flags.go
> +func InitFlags(flagSet *flag.FlagSet, cfg *BasicConfig) {
After a short discussion with @k-gostev, it was decided that flags will remain as they are. The effort is not worth the benefit, as most of the kanto repositories does not follow this convention.

2023-11-15 14:04 UTC, dimitar-dimitrow requested changes

2023-11-16 13:56 UTC, dimitar-dimitrow approved these changes

2023-11-17 15:08 UTC, dimitar-dimitrow approved these changes

2023-11-17 15:12 UTC, k-gostev approved these changes

2023-11-20 09:26 UTC, merged